package applicationSpecific;

import java.awt.Point;

/**
 * Constants that depend on the map file generated by map editor. (Don't change
 * this class without changing the map file)
 */
public class MapEditorData {
	public static final String TOWERS_ALLOWED_LAYER = "towersAllowed";
	public static final String HERO_ALLOWED_LAYER = "heroAllowed";
	public static final String TD_ALLOWED_LAYER = "tdAllowed";
	public static final String MAP_FILE_PATH = Paths.RESOURCES_FILE_PATH
			+ "map2.tmx";

	public static final Point[] TD_START = new Point[]{
			new Point(7, 0), new Point(8,0)};

//	public static final Point[][] TD_CHECKPOINTS = new Point[][] {
//			new Point[] { new Point(2, 14), new Point(9, 14), },
//			new Point[] { new Point(11, 19) } };
	
	public static final Point[][] TD_CHECKPOINTS = new Point[][] {
		new Point[] { new Point(1, 15), new Point(9, 13)},
		new Point[] { new Point(6, 19), new Point(7,20) },
		new Point[] { new Point(9,19),  new Point(9,20)  } };

	public static final Point[] HERO_ENEMIES_START = new Point[] {
			new Point(20, 0), new Point(21, 0), new Point(22, 0),
			new Point(23, 0), new Point(24, 0) };

	public static final Point[] HERO_ENEMIES_CHECKPOINTS = new Point[] {
			new Point(22, 19), new Point(23, 14), new Point(18, 10),
			new Point(25, 9), new Point(25, 4) };

	public static final Point CASTLE_LOCATION = new Point(15, 22);

	// Dependant on map file. Don't change
	public static final int TILE_WIDTH = 40;
	public static final int TILE_HEIGHT = 40;
	public static final int WIDTH_IN_TILES = 30;
	public static final int HEIGHT_IN_TILES = 23;
	public static final int PIXEL_WIDTH = TILE_WIDTH * WIDTH_IN_TILES;
	public static final int PIXEL_HEIGHT = TILE_HEIGHT * HEIGHT_IN_TILES;
}
